Resources:
  CardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.cardstableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: cardId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: cardId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  CartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.carttableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  MenuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.menutableName}
      AttributeDefinitions:
        - AttributeName: menuID
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: menuID
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.transactiontableName}
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
